---

- hosts: synapse

  tasks:
    - apt: update_cache=yes
    - name: install basic packages that we want to be on all nodes
      action: apt pkg={{item}} state=installed
      with_items:
       - joe
       - tcpdump
       - tshark
       - wget
       - git
       - vim
       - locate
       - pwgen

- include: synapse.yml
- include: coturn.yml
- include: nginx.yml
- include: postgres.yml
