---

    - name: Install packages needed to compile coturn server
      action: "apt pkg={{item}} state=installed"
      with_items:
       - gcc
       - make
       - autoconf
       - libevent-dev
       - libsqlite3-dev

    - name: Clone coturn from github
      git: repo=https://github.com/coturn/coturn.git dest=/usr/src/coturn

    - name: Compile and install coturn
      command: "./configure && make && make install"
      args:
        chdir: /usr/src/coturn

    - name: Install turnserver config
      template:
        src: etc/turnserver.conf.j2
        dest: /etc/turnserver.conf
      notify: "Restart turn server"

    - name: Install systemd service
      template:
        src: etc/systemd/system/turnserver.service.j2
        dest: /etc/systemd/system/turnserver.service
        mode: 0644
      notify:
        - "Reload systemctl config"
        - "Restart turn server"

    - name: Enabling coturn service at boot
      command: systemctl enable mxisd