---

- name: Install packages needed to compile coturn server
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
   - gcc
   - make
   - autoconf
   - libevent-dev
   - libsqlite3-dev

- name: Create coturn install dir
  file:
    path: "{{ turn_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Download and extract coturn
  unarchive:
    src: "{{ turn_tarball_url }}"
    dest: "{{ turn_path }}"
    owner: root
    group: root
    copy: no
    creates: "{{ turn_path }}/{{ turn_archive }}"
  register: turn_download

- name: Compile and install coturn
  command: "./configure && make && make install"
  args:
    chdir: "{{ turn_path }}/{{ turn_archive }}"
  when: turn_download.changed

- name: Install turnserver config
  template:
    src: etc/turnserver.conf.j2
    dest: /etc/turnserver.conf
  notify: 
    - restart turn server

- name: Install systemd service
  template:
    src: etc/systemd/system/turnserver.service.j2
    dest: /etc/systemd/system/turnserver.service
    mode: 0644
  notify:
    - reload systemctl daemon
    - restart turn server

- name: Configure local coturn turn_uris
  lineinfile: "dest={{ synapse_path }}/homeserver.yaml"
  args:
    regexp: "^turn_uris:"
    line: "turn_uris: [ \"turn:{{ hostname }}:3478?transport=udp\", \"turn:{{ hostname }}:3478?transport=tcp\" ]"
  when: install_turnserver|bool == true and not ansible_check_mode
  notify:
    - restart synapse
