---

- name: Update apt cache
  apt: update_cache=yes

- name: install basic packages that we want to be on all nodes
  apt: "pkg={{item}} state=installed"
  with_items:
    - wget
    - git

- include: openssl.yml
  when: generate_DH_params

- include: synapse.yml
  tags: synapse
- include: coturn.yml
  when: install_turnserver|bool == true
  tags: turnserver
- include: nginx.yml
- include: postgres.yml
- include: mxisd.yml
  when: install_mxisd|bool == true
- include: riot.im.yml
  tags: riot
