---

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: Making sure the man8 folder exists
  file:
    path: /usr/share/man/man8
    state: directory
    mode: 0755

- name: install basic packages
  apt:
    name:
      - wget
      - git
      - openssl
    state: present

- name: Import synapse tasks
  import_tasks: synapse.yml
  when: install_synapse
  tags: synapse

- name: Import tunrserver tasks
  import_tasks: coturn.yml
  when: install_turnserver
  tags: turnserver

- name: Import nginx tasls
  import_tasks: nginx.yml
  when: install_reverseproxy
  tags: nginx

- name: Import postgres tasks
  import_tasks: postgres.yml
  when: install_postgres
  tags: postgres

- name: Import mxisd tasks
  import_tasks: mxisd.yml
  when: install_mxisd
  tags: mxisd

- name: Import riot.im tasks
  import_tasks: riot.im.yml
  when: install_riot
  tags: riot
