---

- name: Installing packages needed for the reverse proxy
  apt:
    name: nginx
    state: present
  when: nginx_install_package

- name: Test if nginx synapse config exists
  stat:
    path: /etc/nginx/sites-available/synapse
  register: nginx_stats_synapse

- name: Install nginx conf for lets encrypt
  template:
    src:  etc/nginx/sites-available/synapse-le.j2
    dest: /etc/nginx/sites-available/synapse
  notify:
    - restart nginx
  when: install_letsencrypt and nginx_stats_synapse.stat.exists == False

- name: Install nginx conf for synapse
  template:
    src:  etc/nginx/sites-available/synapse.j2
    dest: /etc/nginx/sites-available/synapse
  notify:
    - restart nginx
  when: not install_letsencrypt

- name: Enable the vhost (symlink)
  file:
    src: /etc/nginx/sites-available/synapse
    dest: /etc/nginx/sites-enabled/synapse
    state: link
  notify:
    - restart nginx
  when: not ansible_check_mode

- name: Remove default vhost symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx

- name: Flush handlers
  meta: flush_handlers