---

- name: Installing packages needed for the reverse proxy
  apt:
    name: nginx
    state: present
  when: install_nginx_package|bool == true

- name: Create required matrix dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  with_items:
    - "{{ riot_path }}/.well-known"

- name: Install nginx conf
  template:
    src:  etc/nginx/sites-available/synapse.j2
    dest: /etc/nginx/sites-available/synapse
  notify:
   - restart nginx

- name: Enable the vhost (symlink)
  file:
    src: /etc/nginx/sites-available/synapse
    dest: /etc/nginx/sites-enabled/synapse
    state: link
  notify:
    - restart nginx
  when: not ansible_check_mode

- name: Remove default vhost symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx