---

- name: Installing packages needed for the reverse proxy
  apt:
    name: nginx
    state: present
  when: install_nginx_package

- name: Install nginx conf for synapse
  template:
    src:  etc/nginx/sites-available/synapse.j2
    dest: /etc/nginx/sites-available/synapse
  notify:
   - restart nginx

- name: Enable the vhost (symlink)
  file:
    src: /etc/nginx/sites-available/synapse
    dest: /etc/nginx/sites-enabled/synapse
    state: link
  notify:
    - restart nginx
  when: not ansible_check_mode

- name: Remove default vhost symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx