---

- name: Install postgresql
  apt:
    name:
      - libpq-dev
      - postgresql
      - python-psycopg2
    state: present

- name: Install psycopg2 into the python venv
  pip:
    name: psycopg2
    virtualenv: "{{ synapse_path }}"
    extra_args: '--upgrade'

- name: Start postgresql unit
  service:
    name: postgresql
    state: started

- name: Creating synapse user in postgres
  postgresql_user:
    name: "{{ username }}"
    password: "{{ database_secret }}"
  become: true
  become_user: postgres
  when: not ansible_check_mode

- name: Creating the database
  postgresql_db:
    name: homeserver
    encoding: UTF-8
    #lc_collate: en_US.UTF-8
    #lc_ctype: en_US.UTF-8
    template: template0
    owner: synapse
  become: true
  become_user: postgres
  when: not ansible_check_mode

- name: Stop synapse
  service:
    name: synapse.service
    state: stopped
  when: make_migration

- name: Patch the conf file to add pgsql database
  lineinfile:
    dest: "{{ synapse_path }}/homeserver.yaml"
    regexp: '(.*)name: "sqlite3"'
    line: '\1name: "psycopg2"'
    backrefs: yes
  when: not ansible_check_mode

- name: Add the args to connect to the db
  lineinfile:
    dest: "{{ synapse_path }}/homeserver.yaml"
    regexp: '(.*)database: "(.*)homeserver.db"'
    line: '\1user: "{{ username }}"\n\1password: "{{ database_secret }}"\n\1database: "homeserver"\n\1host: "localhost"\n\1cp_min: 5\n\1cp_max: 10'
    backrefs: yes
  when: not ansible_check_mode

- name: Migrate the database
  command: "{{ synapse_path }}/bin/synapse_port_db --sqlite-database homeserver.db --postgres-config homeserver.yaml"
  args:
    chdir: "{{ synapse_path }}"
  when: make_migration
  notify:
    - restart synapse