---

- name: Install packages required by synapse
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
   - build-essential
   - python3-dev
   - libffi-dev
   - python3-pip
   - python3-setuptools
   - sqlite3
   - libssl-dev
   - python3-virtualenv
   - python3-openssl
   - libjpeg-dev
   - python3-lxml
   - libxslt1-dev
   - jq

- name: Create synapse user
  user: 
    name: "{{ username }}"
    shell: /bin/bash
    comment: "{{ username }}"

- name: Create virtualenv
  command: virtualenv -p python3 {{ synapse_path }}
  args:
    chdir: "/home/{{ username }}"
    creates: "{{ synapse_path }}/"

- name: PIP to upgrade setup tools
  pip: 
    name: setuptools
    virtualenv: "{{ synapse_path }}"
    extra_args: '--upgrade'

- name: PIP to install needed dependencies into virtualenv
  pip: 
    name: "{{ item }}"
    virtualenv: "{{ synapse_path }}"
  with_items:
   - cryptography
   - pyasn1_modules
   - characteristic
   - simplejson
   - canonicaljson
   - enum34
   - ipaddress
   - lxml
   - netaddr

- name: PIP to install synapse from Git Repo into virtualenv
  pip:
    name: "{{ git_repo }}"
    virtualenv: "{{ synapse_path }}"
  notify:
    - restart synapse

#- name: PIP rollback to ldap3 v1.4 (hotfix)
#  pip: name="ldap3==1.4" virtualenv="/home/{{ username }}/.synapse"

- name: Generate homeserver.yaml config file
  shell: ". bin/activate && python -m synapse.app.homeserver --server-name {{ domain }} --config-path homeserver.yaml --generate-config --report-stats=yes"
  args:
    chdir: "{{ synapse_path }}/"
    creates: "{{ synapse_path }}/homeserver.yaml"

- name: Configure homeserver.yaml template
  template:
    src: homeserver.yaml.j2
    dest: "{{ synapse_path }}/homeserver.yaml"
    mode: 0644
  notify:
    - restart synapse

- name: Creating mail template folders
  file:
    path: "{{ synapse_path }}/res/templates"
    state: directory
    mode: 0755
  when: mail|bool == true

- name: Downloading Mail templates{{ synapse_path }}
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dst }}"
  with_items:
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/mail-Vector.css', dst: '{{ synapse_path }}/res/templates/mail-Vector.css' }
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/mail.css', dst: '{{ synapse_path }}/res/templates/mail.css' }
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/notif.html', dst: '{{ synapse_path }}/res/templates/notif.html' }
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/notif.txt', dst: '{{ synapse_path }}/res/templates/notif.txt' }
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/notif_mail.html', dst: '{{ synapse_path }}/res/templates/notif_mail.html' }
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/notif_mail.txt', dst: '{{ synapse_path }}/res/templates/notif_mail.txt' }
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/room.html', dst: '{{ synapse_path }}/res/templates/room.html' }
    - { src: 'https://raw.githubusercontent.com/matrix-org/synapse/master/res/templates/room.txt', dst: '{{ synapse_path }}/res/templates/room.txt' }
  when: mail|bool == true

- name: Set permissions
  file:
    path: '/home/{{ username }}/.synapse'
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Install synapse systemd conf
  template:
      src: etc/systemd/system/synapse.service.j2
      dest: /etc/systemd/system/synapse.service
      mode: 0644
  notify:
      - reload systemctl daemon
      - restart synapse